/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthOrganizerRouteImport } from './routes/auth.organizer'
import { Route as AuthParticipantRouteImport } from './routes/auth.participant'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerCreateRouteImport } from './routes/organizer.create'
import { Route as OrganizerFoodRouteImport } from './routes/organizer.food'
import { Route as OrganizerParticipantsRouteImport } from './routes/organizer.participants'
import { Route as OrganizerPptAnalysisRouteImport } from './routes/organizer.ppt-analysis'
import { Route as OrganizerSeatingRouteImport } from './routes/organizer.seating'
import { Route as OrganizerSettingsRouteImport } from './routes/organizer.settings'
import { Route as ParticipantIndexRouteImport } from './routes/participant.index'
import { Route as ParticipantExploreRouteImport } from './routes/participant.explore'
import { Route as ParticipantProfileRouteImport } from './routes/participant.profile'
import { Route as ParticipantQrRouteImport } from './routes/participant.qr'
import { Route as ParticipantRegistrationsRouteImport } from './routes/participant.registrations'
import { Route as ParticipantSettingsRouteImport } from './routes/participant.settings'
import { Route as ParticipantHackathonIdRouteImport } from './routes/participant.hackathon.$id'
import { Route as ParticipantRegisterIdRouteImport } from './routes/participant.register.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizerRoute = AuthOrganizerRouteImport.update({
  id: '/auth/organizer',
  path: '/auth/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthParticipantRoute = AuthParticipantRouteImport.update({
  id: '/auth/participant',
  path: '/auth/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerFoodRoute = OrganizerFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerParticipantsRoute = OrganizerParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPptAnalysisRoute = OrganizerPptAnalysisRouteImport.update({
  id: '/ppt-analysis',
  path: '/ppt-analysis',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerSeatingRoute = OrganizerSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerSettingsRoute = OrganizerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrganizerRoute,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantExploreRoute = ParticipantExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantProfileRoute = ParticipantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantQrRoute = ParticipantQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantRegistrationsRoute =
  ParticipantRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => ParticipantRoute,
  } as any)
const ParticipantSettingsRoute = ParticipantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantHackathonIdRoute = ParticipantHackathonIdRouteImport.update({
  id: '/hackathon/$id',
  path: '/hackathon/$id',
  getParentRoute: () => ParticipantRoute,
} as any)
const ParticipantRegisterIdRoute = ParticipantRegisterIdRouteImport.update({
  id: '/register/$id',
  path: '/register/$id',
  getParentRoute: () => ParticipantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/participant': typeof ParticipantRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/organizer': typeof AuthOrganizerRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/food': typeof OrganizerFoodRoute
  '/organizer/participants': typeof OrganizerParticipantsRoute
  '/organizer/ppt-analysis': typeof OrganizerPptAnalysisRoute
  '/organizer/seating': typeof OrganizerSeatingRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/participant/explore': typeof ParticipantExploreRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/qr': typeof ParticipantQrRoute
  '/participant/registrations': typeof ParticipantRegistrationsRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/participant/hackathon/$id': typeof ParticipantHackathonIdRoute
  '/participant/register/$id': typeof ParticipantRegisterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/organizer': typeof AuthOrganizerRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/food': typeof OrganizerFoodRoute
  '/organizer/participants': typeof OrganizerParticipantsRoute
  '/organizer/ppt-analysis': typeof OrganizerPptAnalysisRoute
  '/organizer/seating': typeof OrganizerSeatingRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/participant/explore': typeof ParticipantExploreRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/qr': typeof ParticipantQrRoute
  '/participant/registrations': typeof ParticipantRegistrationsRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/organizer': typeof OrganizerIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/participant/hackathon/$id': typeof ParticipantHackathonIdRoute
  '/participant/register/$id': typeof ParticipantRegisterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/participant': typeof ParticipantRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/organizer': typeof AuthOrganizerRoute
  '/auth/participant': typeof AuthParticipantRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/organizer/food': typeof OrganizerFoodRoute
  '/organizer/participants': typeof OrganizerParticipantsRoute
  '/organizer/ppt-analysis': typeof OrganizerPptAnalysisRoute
  '/organizer/seating': typeof OrganizerSeatingRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/participant/explore': typeof ParticipantExploreRoute
  '/participant/profile': typeof ParticipantProfileRoute
  '/participant/qr': typeof ParticipantQrRoute
  '/participant/registrations': typeof ParticipantRegistrationsRoute
  '/participant/settings': typeof ParticipantSettingsRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/participant/hackathon/$id': typeof ParticipantHackathonIdRoute
  '/participant/register/$id': typeof ParticipantRegisterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organizer'
    | '/participant'
    | '/sitemap.xml'
    | '/auth/organizer'
    | '/auth/participant'
    | '/organizer/create'
    | '/organizer/food'
    | '/organizer/participants'
    | '/organizer/ppt-analysis'
    | '/organizer/seating'
    | '/organizer/settings'
    | '/participant/explore'
    | '/participant/profile'
    | '/participant/qr'
    | '/participant/registrations'
    | '/participant/settings'
    | '/organizer/'
    | '/participant/'
    | '/participant/hackathon/$id'
    | '/participant/register/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/auth/organizer'
    | '/auth/participant'
    | '/organizer/create'
    | '/organizer/food'
    | '/organizer/participants'
    | '/organizer/ppt-analysis'
    | '/organizer/seating'
    | '/organizer/settings'
    | '/participant/explore'
    | '/participant/profile'
    | '/participant/qr'
    | '/participant/registrations'
    | '/participant/settings'
    | '/organizer'
    | '/participant'
    | '/participant/hackathon/$id'
    | '/participant/register/$id'
  id:
    | '__root__'
    | '/'
    | '/organizer'
    | '/participant'
    | '/sitemap.xml'
    | '/auth/organizer'
    | '/auth/participant'
    | '/organizer/create'
    | '/organizer/food'
    | '/organizer/participants'
    | '/organizer/ppt-analysis'
    | '/organizer/seating'
    | '/organizer/settings'
    | '/participant/explore'
    | '/participant/profile'
    | '/participant/qr'
    | '/participant/registrations'
    | '/participant/settings'
    | '/organizer/'
    | '/participant/'
    | '/participant/hackathon/$id'
    | '/participant/register/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  ParticipantRoute: typeof ParticipantRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthOrganizerRoute: typeof AuthOrganizerRoute
  AuthParticipantRoute: typeof AuthParticipantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/organizer': {
      id: '/auth/organizer'
      path: '/auth/organizer'
      fullPath: '/auth/organizer'
      preLoaderRoute: typeof AuthOrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/participant': {
      id: '/auth/participant'
      path: '/auth/participant'
      fullPath: '/auth/participant'
      preLoaderRoute: typeof AuthParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/create': {
      id: '/organizer/create'
      path: '/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/food': {
      id: '/organizer/food'
      path: '/food'
      fullPath: '/organizer/food'
      preLoaderRoute: typeof OrganizerFoodRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/participants': {
      id: '/organizer/participants'
      path: '/participants'
      fullPath: '/organizer/participants'
      preLoaderRoute: typeof OrganizerParticipantsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/ppt-analysis': {
      id: '/organizer/ppt-analysis'
      path: '/ppt-analysis'
      fullPath: '/organizer/ppt-analysis'
      preLoaderRoute: typeof OrganizerPptAnalysisRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/seating': {
      id: '/organizer/seating'
      path: '/seating'
      fullPath: '/organizer/seating'
      preLoaderRoute: typeof OrganizerSeatingRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/settings': {
      id: '/organizer/settings'
      path: '/settings'
      fullPath: '/organizer/settings'
      preLoaderRoute: typeof OrganizerSettingsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/participant/': {
      id: '/participant/'
      path: '/'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/explore': {
      id: '/participant/explore'
      path: '/explore'
      fullPath: '/participant/explore'
      preLoaderRoute: typeof ParticipantExploreRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/profile': {
      id: '/participant/profile'
      path: '/profile'
      fullPath: '/participant/profile'
      preLoaderRoute: typeof ParticipantProfileRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/qr': {
      id: '/participant/qr'
      path: '/qr'
      fullPath: '/participant/qr'
      preLoaderRoute: typeof ParticipantQrRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/registrations': {
      id: '/participant/registrations'
      path: '/registrations'
      fullPath: '/participant/registrations'
      preLoaderRoute: typeof ParticipantRegistrationsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/settings': {
      id: '/participant/settings'
      path: '/settings'
      fullPath: '/participant/settings'
      preLoaderRoute: typeof ParticipantSettingsRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/hackathon/$id': {
      id: '/participant/hackathon/$id'
      path: '/hackathon/$id'
      fullPath: '/participant/hackathon/$id'
      preLoaderRoute: typeof ParticipantHackathonIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
    '/participant/register/$id': {
      id: '/participant/register/$id'
      path: '/register/$id'
      fullPath: '/participant/register/$id'
      preLoaderRoute: typeof ParticipantRegisterIdRouteImport
      parentRoute: typeof ParticipantRoute
    }
  }
}

interface OrganizerRouteChildren {
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerFoodRoute: typeof OrganizerFoodRoute
  OrganizerParticipantsRoute: typeof OrganizerParticipantsRoute
  OrganizerPptAnalysisRoute: typeof OrganizerPptAnalysisRoute
  OrganizerSeatingRoute: typeof OrganizerSeatingRoute
  OrganizerSettingsRoute: typeof OrganizerSettingsRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerFoodRoute: OrganizerFoodRoute,
  OrganizerParticipantsRoute: OrganizerParticipantsRoute,
  OrganizerPptAnalysisRoute: OrganizerPptAnalysisRoute,
  OrganizerSeatingRoute: OrganizerSeatingRoute,
  OrganizerSettingsRoute: OrganizerSettingsRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface ParticipantRouteChildren {
  ParticipantExploreRoute: typeof ParticipantExploreRoute
  ParticipantProfileRoute: typeof ParticipantProfileRoute
  ParticipantQrRoute: typeof ParticipantQrRoute
  ParticipantRegistrationsRoute: typeof ParticipantRegistrationsRoute
  ParticipantSettingsRoute: typeof ParticipantSettingsRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  ParticipantHackathonIdRoute: typeof ParticipantHackathonIdRoute
  ParticipantRegisterIdRoute: typeof ParticipantRegisterIdRoute
}

const ParticipantRouteChildren: ParticipantRouteChildren = {
  ParticipantExploreRoute: ParticipantExploreRoute,
  ParticipantProfileRoute: ParticipantProfileRoute,
  ParticipantQrRoute: ParticipantQrRoute,
  ParticipantRegistrationsRoute: ParticipantRegistrationsRoute,
  ParticipantSettingsRoute: ParticipantSettingsRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
  ParticipantHackathonIdRoute: ParticipantHackathonIdRoute,
  ParticipantRegisterIdRoute: ParticipantRegisterIdRoute,
}

const ParticipantRouteWithChildren = ParticipantRoute._addFileChildren(
  ParticipantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  ParticipantRoute: ParticipantRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthOrganizerRoute: AuthOrganizerRoute,
  AuthParticipantRoute: AuthParticipantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
